// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://piuwrlaoxuefmiisuamc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBpdXdybGFveHVlZm1paXN1YW1jIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMxOTc4OTUsImV4cCI6MjA2ODc3Mzg5NX0.JRSZL8vi4tqm1cUddrD9ptYXJGh6_VB02xHZUoaTTPg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});