// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY;

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  console.error('Missing Supabase environment variables:', {
    SUPABASE_URL: SUPABASE_URL ? 'present' : 'missing',
    SUPABASE_PUBLISHABLE_KEY: SUPABASE_PUBLISHABLE_KEY ? 'present' : 'missing',
    env: import.meta.env
  });
  throw new Error('Missing Supabase environment variables. Please check your environment variables in Vercel dashboard.');
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
    storageKey: 'sb-auth-token',
    // Enable PKCE flow for better security
    flowType: 'pkce',
  },
  global: {
    headers: {
      'x-client-info': 'wall-quote-wizard@1.0.0',
    },
  },
  realtime: {
    // Enable realtime for instant session expiration detection
    // This makes session expiration happen automatically in the background
    // instead of waiting for the user to interact with the app
    params: {
      eventsPerSecond: 10,
    },
  },
});